#!/bin/bash

# Reference Paper: 
#   Z. Li, J. Zhang, R. Zhong, B. Bhanu, Y. Chen, Q. Zhang, H. Tang
#   Lightweight and Efficient Image Dehazing Network Guided by Transmission Estimation from Real-world Hazy Scenes
#   Sensors. MDPI, Basel, Switzerland. 1 February 2021 
# Any questions please contact：lizhangray@qq.com


while getopts 'm:t:s:' ARGS
do
case $ARGS in
	m)
		model_path=$OPTARG
		;;
	t)
		test_path=$OPTARG
		;;
	s)
		out_path=$OPTARG
		;;
	--) 
		break
		;;
esac
done




for file in $test_path
do
	echo $file
	python run_bak.py -d $model_path -t $file -o $out_path -e 1
done




echo "Done!!!"
